<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>

<body>
    <script>
        // 1.使用setTimeout模拟异步操作
        // setTimeout(() => {
        //         console.log('Hello,1')
        //         setTimeout(() => {
        //             console.log('Hello,2')
        //             setTimeout(() => {
        //                 console.log('Hello,3')
        //                 setTimeout(() => {
        //                     console.log('Hello,4')
        //                     setTimeout(() => {
        //                         console.log('Hello,5')
        //                     }, 1000);
        //                 }, 1000);
        //             }, 1000);
        //         }, 1000);
        //     }, 1000);

        //Promise避免回调地狱
        //Promise(function(resolve, reject))
        //resolve,reject本身也是函数
        new Promise((resolve, reject) => {
            setTimeout(() => {
                resolve()
            }, 1000);
        }).then(() => {
            console.log('Hello,1')
            return new Promise((resolve, reject) => {
                setTimeout(() => {
                    resolve()
                }, 1000);
            })
        }).then(() => {
            console.log('Hello,2')
            return new Promise((resolve, reject) => {
                setTimeout(() => {
                    resolve()
                }, 1000);
            })
        }).then(() => {
            console.log('Hello,3')
            return new Promise((resolve, reject) => {
                setTimeout(() => {
                    resolve()
                }, 1000);
            })
        }).then(() => {
            console.log('Hello,4')
            return new Promise((resolve, reject) => {
                setTimeout(() => {
                    resolve()
                }, 1000);
            })
        }).then(() => {
            console.log('Hello,5')
        })

        //一般在异步操作下使用Promise
        // new Promise后保存了一些状态信息,然后执行传入到函数
        //在执行传入到回调函数时会传入两个参数,resolve, reject本身也是函数
        //resolve与reject互斥执行
        new Promise((resolve, reject) => {
            setTimeout(() => {
                //成功到时候调用resolve
                //resolve('success')
                
                //失败到时候调用reject
                reject('error')
            }, 1000);
        }).then((data) => {
            console.log(data)
        }).catch((err) => {
            console.log(err)
        })

        //Promise了另外一种形式
        new Promise((resolve, reject) => {
            setTimeout(() => {
                resolve('Hello,Vue.js')
                //reject('error')
            }, 1000);
        }).then((data) => {
            console.log(data)
        }, (err) => {
            console.log(err)
        })

        //Promise链式调用
        new Promise((resolve) => {
            setTimeout(() => {
                resolve('Hello')
            }, 1000);
        }).then(data => {
            return new Promise((resolve) => {
                resolve(data + ',')
            })
        }).then(data => {
            //注意这里写法是new Promise((resolve)=>{})的简写
            return Promise.resolve(data+'Promise')
        }).then(data => {
            return data + '.resolve()'
        }).then(data => {
            //手动抛出异常
            //throw 'error'
            return Promise.reject('error')
        }).then(data => {
            console.log(data)
        }).catch((err) => {
            console.log(err)
        })


        //Promise的all函数使用
        Promise.all([
            new Promise((resolve) => {
                setTimeout(() => {
                    resolve('Hello')
                }, 1000);
            }),
            new Promise((resolve) => {
                setTimeout(() => {
                    resolve('Promise.all()')
                }, 2000);
            }),
        ]).then(resolves=>{
            console.log(resolves[0]+","+resolves[1])
        })

    </script>
</body>

</html>